# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce14de689ffb3fe94431026727ba32f6346ef5501e3ff437cc109f8ee26ed10631fc1f069e15b03479ed2305261b924946916af6ac4eba66879f0f780ee6ab3

test:
  secret_key_base: 244a0d39cf29da867cf6956dc568901b551b6e57eae327335512b1ddb5c064377e1a386627c320d1b9eaa2dd46f9952a0764b33ff4ef020afa62b42a5111d3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
